<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE newtable [
  <!ELEMENT newtable (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (sku?,name?,image?,additionalimage?,category?,price_with_vat?,manufacturer?,mpn?,ean?,instock?,availability?,size?,weight?,color?)+>
  <!ELEMENT sku (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT image (#PCDATA)>
  <!ELEMENT additionalimage (#PCDATA)>
  <!ELEMENT category (#PCDATA)>
  <!ELEMENT price_with_vat (#PCDATA)>
  <!ELEMENT manufacturer (#PCDATA)>
  <!ELEMENT mpn (#PCDATA)>
  <!ELEMENT ean (#PCDATA)>
  <!ELEMENT instock (#PCDATA)>
  <!ELEMENT availability (#PCDATA)>
  <!ELEMENT size (#PCDATA)>
  <!ELEMENT weight (#PCDATA)>
  <!ELEMENT color (#PCDATA)>
]>
<newtable>
  <DATA_RECORD>
    <sku>223005</sku>
    <name>PUMA COLLAGE SOCKS</name>
    <image>https://www.sansirosports.com/product_catalog/groups/8669/14971054_10202213196169006_426538184_o.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/8669/14971054_10202213196169006_426538184_o.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>4.6500001</price_with_vat>
    <manufacturer>PUMA</manufacturer>
    <mpn>223005</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>39-42</size>
    <weight></weight>
    <color>GREY</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>224005</sku>
    <name>PUMA COLLAGE SOCKS</name>
    <image>https://www.sansirosports.com/product_catalog/groups/8670/s-l1600.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/8670/s-l1600.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>3.5</price_with_vat>
    <manufacturer>PUMA</manufacturer>
    <mpn>224005</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>27-30,31-34</size>
    <weight></weight>
    <color>BLUE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>224006</sku>
    <name>PUMA COLLAGE SHIELD</name>
    <image>https://www.sansirosports.com/product_catalog/groups/8671/14959096_10202213195848998_729499845_o.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/8671/14959096_10202213195848998_729499845_o.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>3.5</price_with_vat>
    <manufacturer>PUMA</manufacturer>
    <mpn>224006</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>27-30</size>
    <weight></weight>
    <color>BLUE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>G92578</sku>
    <name>ADIDAS ORIGINALS SLIM DIAMOND G92578</name>
    <image>https://www.sansirosports.com/product_catalog/groups/8980/g92578.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/8980/g92578.jpg</additionalimage>
    <category>ΓΥΝΑΙΚΑ</category>
    <price_with_vat>40</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>G92578</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>XSmall</size>
    <weight></weight>
    <color>ORANGE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>W57005</sku>
    <name>ADIDAS CULTURE SCARF W57005</name>
    <image>https://www.sansirosports.com/product_catalog/groups/8992/W57005.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/8992/W57005.jpg</additionalimage>
    <category>ΑΞΕΣΟΥΑΡ</category>
    <price_with_vat>12.5</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>W57005</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>OSFW</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>O05794</sku>
    <name>ADIDAS ESS SCARF O05794</name>
    <image>https://www.sansirosports.com/product_catalog/groups/8994/O05794.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/8994/O05794.jpg</additionalimage>
    <category>ΑΞΕΣΟΥΑΡ</category>
    <price_with_vat>11</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>O05794</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>OSFW</size>
    <weight></weight>
    <color>WHITE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>Z56222</sku>
    <name>ADIDAS SANTOS 3-STRIPE Z56222</name>
    <image>https://www.sansirosports.com/product_catalog/groups/9056/Z56222.png</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/9056/Z56222.png</additionalimage>
    <category>ΠΟΔΟΣΦΑΙΡΟ</category>
    <price_with_vat>8.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>Z56222</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>46-48</size>
    <weight></weight>
    <color>WHITE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>620656</sku>
    <name>ADIDAS SOCK HOLDER 620656</name>
    <image>https://www.sansirosports.com/product_catalog/groups/9062/620656.png</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/9062/620656.png</additionalimage>
    <category>ΠΟΔΟΣΦΑΙΡΟ</category>
    <price_with_vat>5.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>620656</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>ONE SIZE</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>615190</sku>
    <name>ADIDAS GUARD STAYS 615190</name>
    <image>https://www.sansirosports.com/product_catalog/groups/9063/615190.png</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/9063/615190.png</additionalimage>
    <category>ΠΟΔΟΣΦΑΙΡΟ</category>
    <price_with_vat>7.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>615190</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>ONE SIZE</size>
    <weight></weight>
    <color>WHITE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>4340109</sku>
    <name>SLIM SLEEVELES</name>
    <image>https://www.sansirosports.com/product_catalog/groups/9410/04340109.png</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/9410/04340109.png</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>8.39999962</price_with_vat>
    <manufacturer>BODY ACTION</manufacturer>
    <mpn>4340109</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>Medium</size>
    <weight></weight>
    <color>YELLOW</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>5340707</sku>
    <name>SLIM T-SHIRT</name>
    <image>https://www.sansirosports.com/product_catalog/groups/9411/05340707.png</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/9411/05340707.png</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>9.19999981</price_with_vat>
    <manufacturer>BODY ACTION</manufacturer>
    <mpn>5340707</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>Medium</size>
    <weight></weight>
    <color>GREEN</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>G70910</sku>
    <name>ADIDAS AIR PUMP G70910</name>
    <image>https://www.sansirosports.com/product_catalog/groups/9784/G70910.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/9784/G70910.jpg</additionalimage>
    <category>ΠΟΔΟΣΦΑΙΡΟ</category>
    <price_with_vat>9.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>G70910</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>ONE SIZE</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>AZ3683</sku>
    <name>ADIDAS ACE TRAINING GLOVES AZ3683</name>
    <image>https://www.sansirosports.com/product_catalog/groups/10620/az3683_2.png</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/10620/az3683_2.png</additionalimage>
    <category>ΠΟΔΟΣΦΑΙΡΟ</category>
    <price_with_vat>24.95000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>AZ3683</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>10</size>
    <weight></weight>
    <color>RED</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>AY9102</sku>
    <name>ADIDAS ESSENTIAL PRINT SHORTS AY9102</name>
    <image>https://www.sansirosports.com/product_catalog/groups/10780/AY9102.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/10780/AY9102.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>14</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>AY9102</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>XSmall</size>
    <weight></weight>
    <color>GREY</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BP5327</sku>
    <name>ADIDAS MINI SUMMER SET BP5327</name>
    <image>https://www.sansirosports.com/product_catalog/groups/10916/BP5327.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/10916/BP5327.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>14</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BP5327</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>6-9 Months / 74</size>
    <weight></weight>
    <color>BLUE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BQ9636</sku>
    <name>ADIDAS MEN CLOTHING ESSENTIALS LINEAR FLEECE ZIP HOODIE BQ9636</name>
    <image>https://www.sansirosports.com/product_catalog/groups/11142/BQ9636.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/11142/BQ9636.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>30</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BQ9636</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>Small</size>
    <weight></weight>
    <color>GREY</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BS2205</sku>
    <name>ADIDAS ID T-SHIRT LONG SLEEVES BS2205</name>
    <image>https://www.sansirosports.com/product_catalog/groups/11159/BS2205.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/11159/BS2205.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>19.95000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BS2205</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>Large,Small,XLarge,XXLarge</size>
    <weight></weight>
    <color>WHITE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>S98775</sku>
    <name>ADIDAS MEN CLOTHING ESSENTIALS LINEAR PULLOVER HOODIE S98775</name>
    <image>https://www.sansirosports.com/product_catalog/groups/11176/S98775.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/11176/S98775.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>30</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>S98775</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>XLarge,XXLarge</size>
    <weight></weight>
    <color>GREY</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>S94922</sku>
    <name>ADIDAS REAL MADRID ORGANIZER S94922</name>
    <image>https://www.sansirosports.com/product_catalog/groups/11209/S94922.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/11209/S94922.jpg</additionalimage>
    <category>ΑΞΕΣΟΥΑΡ</category>
    <price_with_vat>17.95000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>S94922</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>ONE SIZE</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>AA2313</sku>
    <name>ADIDAS PERFORMANCE NO-SHOW THIN SOCKS 3PAIR AA2313</name>
    <image>https://www.sansirosports.com/product_catalog/groups/11218/AA2313.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/11218/AA2313.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>8.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>AA2313</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>19-22,31-34,47-50</size>
    <weight></weight>
    <color>MULTI</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>861890</sku>
    <name>SIGG MINNIE MOUSE 0.4L</name>
    <image>https://www.sansirosports.com/product_catalog/groups/25453/861890.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/25453/861890.jpg</additionalimage>
    <category>ΑΞΕΣΟΥΑΡ</category>
    <price_with_vat>24.95000076</price_with_vat>
    <manufacturer>SIGG</manufacturer>
    <mpn>861890</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>400ML</size>
    <weight></weight>
    <color>MULTI</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>AA2312</sku>
    <name>ADIDAS PERFORMANCE NO-SHOW THIN SOCKS 3PAIR AA2312</name>
    <image>https://www.sansirosports.com/product_catalog/groups/11219/AA2312.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/11219/AA2312.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>8.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>AA2312</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>19-22,23-26,35-38</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>AW4883</sku>
    <name>ADIDAS NEO VS ADVANTAGE KIDS AW4883</name>
    <image>https://www.sansirosports.com/product_catalog/groups/11273/aw4883.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/11273/aw4883.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>23.95000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>AW4883</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>30.5</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BJ9297</sku>
    <name>ADIDAS WOMEN STELLASPORT TIGHTS BJ9297</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12356/BJ9297.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12356/BJ9297.jpg</additionalimage>
    <category>ΓΥΝΑΙΚΑ</category>
    <price_with_vat>27.5</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BJ9297</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>XSmall</size>
    <weight></weight>
    <color>MULTI</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BJ9525</sku>
    <name>ADIDAS GIRLS TIGHTS BJ9525</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12357/BJ9525.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12357/BJ9525.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>15</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BJ9525</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>13-14 Years / 164</size>
    <weight></weight>
    <color>BLUE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BJ9526</sku>
    <name>ADIDAS GIRLS TIGHTS BJ9526</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12358/BJ9526.jpeg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12358/BJ9526.jpeg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>15</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BJ9526</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>14-15 Years / 170</size>
    <weight></weight>
    <color>GREY</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BK3484</sku>
    <name>ADIDAS BOYS LINEAR PANTS BK3484</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12363/BK3484.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12363/BK3484.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>17.45000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BK3484</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>14-15 Years / 170</size>
    <weight></weight>
    <color>BLUE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BP8581</sku>
    <name>ADIDAS GIRLS LINEAR HOODIE BP8581</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12369/BP8581.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12369/BP8581.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>22.45000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BP8581</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>5-6 Years / 116</size>
    <weight></weight>
    <color>RED</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BP8582</sku>
    <name>ADIDAS GIRLS LINEAR HOODIE BP8582</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12370/BP8582.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12370/BP8582.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>22.45000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BP8582</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>5-6 Years / 116</size>
    <weight></weight>
    <color>PINK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BQ2915</sku>
    <name>ADIDAS BOYS MESSI PERFORMANCE TIRO PANTS BQ2915</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12383/BQ2915.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12383/BQ2915.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>22.45000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BQ2915</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>13-14 Years / 164</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>172707706</sku>
    <name>GSA GEAR WOMEN LEGGINGS 172707706</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12749/1.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12749/1.jpg</additionalimage>
    <category>ΓΥΝΑΙΚΑ</category>
    <price_with_vat>10</price_with_vat>
    <manufacturer>GSA SPORT</manufacturer>
    <mpn>172707706</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>XSmall</size>
    <weight></weight>
    <color>MULTI</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>372700503</sku>
    <name>GSA GEAR WOMEN GLORY JOGGING PANTS 372700503</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12771/372700503.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12771/372700503.jpg</additionalimage>
    <category>ΓΥΝΑΙΚΑ</category>
    <price_with_vat>15.94999981</price_with_vat>
    <manufacturer>GSA SPORT</manufacturer>
    <mpn>372700503</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>XLarge</size>
    <weight></weight>
    <color>BLUE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>372700529</sku>
    <name>GSA WOMEN GLORY JOGGING PANTS 372700529</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12773/372700529.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12773/372700529.jpg</additionalimage>
    <category>ΓΥΝΑΙΚΑ</category>
    <price_with_vat>15.94999981</price_with_vat>
    <manufacturer>GSA SPORT</manufacturer>
    <mpn>372700529</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>XLarge</size>
    <weight></weight>
    <color>PURPLE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>AA2298</sku>
    <name>ADIDAS 3 STRIPES SOCKS AA2298</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12782/aa2298.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12782/aa2298.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>11.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>AA2298</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>19-22,23-26,27-30</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>AA2299</sku>
    <name>ADIDAS 3 STRIPES SOCKS AA2299</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12783/aa2299.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12783/aa2299.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>11.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>AA2299</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>19-22,23-26</size>
    <weight></weight>
    <color>MULTI</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>AI6720</sku>
    <name>ADIDAS MANCHESTER UNITED FC HOIME REPLICA JERSEY TEE AI6720</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12786/ai6720.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12786/ai6720.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>44.95000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>AI6720</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>Large,Small,XLarge,XXLarge</size>
    <weight></weight>
    <color>RED</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BK2869</sku>
    <name>ADIDAS PERFORMANCE OLYMPIACOS KIDS TEE BK2869</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12797/bk2869.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12797/bk2869.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>27.5</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BK2869</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>13-14 Years / 164,7-8 Years / 128</size>
    <weight></weight>
    <color>ORANGE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BQ4243</sku>
    <name>ADIDAS MEN CYTINS PADDED JACKET BQ4243</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12802/bq4243.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12802/bq4243.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>44.95000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BQ4243</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>Small</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>BQ4244</sku>
    <name>ADIDAS MEN CYTINS PADDED JACKET BQ4244</name>
    <image>https://www.sansirosports.com/product_catalog/groups/12803/bq4244.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/12803/bq4244.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>44.95000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>BQ4244</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>Small,XSmall</size>
    <weight></weight>
    <color>BLUE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>3717004010</sku>
    <name>GSA GEAR MEN GLORY CREW NECK 3717004010</name>
    <image>https://www.sansirosports.com/product_catalog/groups/13125/3717004010.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/13125/3717004010.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>36</price_with_vat>
    <manufacturer>GSA SPORT</manufacturer>
    <mpn>3717004010</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>XLarge</size>
    <weight></weight>
    <color>RED</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>CF6925</sku>
    <name>ADIDAS ACCESSORIES TENNIS HEADBAND CF6925</name>
    <image>https://www.sansirosports.com/product_catalog/groups/13421/cf6925.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/13421/cf6925.jpg</additionalimage>
    <category>ΑΞΕΣΟΥΑΡ</category>
    <price_with_vat>9.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>CF6925</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>OSFM,OSFY</size>
    <weight></weight>
    <color>WHITE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>CQ0027</sku>
    <name>ADIDAS INFANTS GIRLS RUNNING ALTARUN CF SHOES CQ0027</name>
    <image>https://www.sansirosports.com/product_catalog/groups/13438/cq0027.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/13438/cq0027.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>16.75</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>CQ0027</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>20</size>
    <weight></weight>
    <color>PURPLE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>CQ0036</sku>
    <name>ADIDAS KIDS GIRLS RUNNING ALTARUN CF SHOES CQ0036</name>
    <image>https://www.sansirosports.com/product_catalog/groups/13444/cq0036.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/13444/cq0036.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>17.45000076</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>CQ0036</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>38 2/3</size>
    <weight></weight>
    <color>PURPLE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>CV7155</sku>
    <name>ADIDAS KIDS GIRLS TRAINING ANKLE SOCKS 3 PAIRS CV7155</name>
    <image>https://www.sansirosports.com/product_catalog/groups/13449/cv7155.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/13449/cv7155.jpg</additionalimage>
    <category>ΠΑΙΔΙ</category>
    <price_with_vat>9.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>CV7155</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>35-38</size>
    <weight></weight>
    <color>WHITE</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>CV7409</sku>
    <name>ADIDAS TRAINING PERFORMANCE INVISIBLE SOCKS 3 PAIRS CV7409</name>
    <image>https://www.sansirosports.com/product_catalog/groups/13451/cv7409.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/13451/cv7409.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>9.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>CV7409</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>35-38</size>
    <weight></weight>
    <color>BLACK</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>CV7410</sku>
    <name>ADIDAS TRAINING PERFORMANCE INVISIBLE SOCKS 3 PAIRS CV7410</name>
    <image>https://www.sansirosports.com/product_catalog/groups/13452/cv7410.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/13452/cv7410.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>9.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>CV7410</mpn>
    <ean></ean>
    <instock>111</instock>
    <availability>Παράδοση 1 έως 3 ημέρες</availability>
    <size>35-38</size>
    <weight></weight>
    <color>MULTI</color>
  </DATA_RECORD>
  <DATA_RECORD>
    <sku>CV8132</sku>
    <name>ADIDAS TRAINING PERFORMANCE NO-SHOW THIN SOCKS 6 PAIRS CV8132</name>
    <image>https://www.sansirosports.com/product_catalog/groups/13454/cv8132.jpg</image>
    <additionalimage>https://www.sansirosports.com/product_catalog/groups/13454/cv8132.jpg</additionalimage>
    <category>ΑΝΔΡΑΣ</category>
    <price_with_vat>14.94999981</price_with_vat>
    <manufacturer>ADIDAS</manufacturer>
    <mpn>CV8132</mpn>
    <ean></ean>
    <instock>111</instock>